/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSubcategoriesRouteImport } from './routes/admin.subcategories'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsBrandIdRouteImport } from './routes/brands.$brandId'
import { Route as CatCatIdRouteImport } from './routes/cat.$catId'
import { Route as SubcatSubcatIdRouteImport } from './routes/subcat.$subcatId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubcategoriesRoute = AdminSubcategoriesRouteImport.update({
  id: '/subcategories',
  path: '/subcategories',
  getParentRoute: () => AdminRoute,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const CatCatIdRoute = CatCatIdRouteImport.update({
  id: '/cat/$catId',
  path: '/cat/$catId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubcatSubcatIdRoute = SubcatSubcatIdRouteImport.update({
  id: '/subcat/$subcatId',
  path: '/subcat/$subcatId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/cat/$catId': typeof CatCatIdRoute
  '/subcat/$subcatId': typeof SubcatSubcatIdRoute
  '/admin/': typeof AdminIndexRoute
  '/brands/': typeof BrandsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/cat/$catId': typeof CatCatIdRoute
  '/subcat/$subcatId': typeof SubcatSubcatIdRoute
  '/admin': typeof AdminIndexRoute
  '/brands': typeof BrandsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subcategories': typeof AdminSubcategoriesRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/cat/$catId': typeof CatCatIdRoute
  '/subcat/$subcatId': typeof SubcatSubcatIdRoute
  '/admin/': typeof AdminIndexRoute
  '/brands/': typeof BrandsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/categories'
    | '/login'
    | '/products'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subcategories'
    | '/brands/$brandId'
    | '/cat/$catId'
    | '/subcat/$subcatId'
    | '/admin/'
    | '/brands/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/login'
    | '/products'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subcategories'
    | '/brands/$brandId'
    | '/cat/$catId'
    | '/subcat/$subcatId'
    | '/admin'
    | '/brands'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/categories'
    | '/login'
    | '/products'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subcategories'
    | '/brands/$brandId'
    | '/cat/$catId'
    | '/subcat/$subcatId'
    | '/admin/'
    | '/brands/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  BrandsBrandIdRoute: typeof BrandsBrandIdRoute
  CatCatIdRoute: typeof CatCatIdRoute
  SubcatSubcatIdRoute: typeof SubcatSubcatIdRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subcategories': {
      id: '/admin/subcategories'
      path: '/subcategories'
      fullPath: '/admin/subcategories'
      preLoaderRoute: typeof AdminSubcategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId': {
      id: '/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cat/$catId': {
      id: '/cat/$catId'
      path: '/cat/$catId'
      fullPath: '/cat/$catId'
      preLoaderRoute: typeof CatCatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subcat/$subcatId': {
      id: '/subcat/$subcatId'
      path: '/subcat/$subcatId'
      fullPath: '/subcat/$subcatId'
      preLoaderRoute: typeof SubcatSubcatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubcategoriesRoute: typeof AdminSubcategoriesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBrandsRoute: AdminBrandsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubcategoriesRoute: AdminSubcategoriesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  BrandsBrandIdRoute: BrandsBrandIdRoute,
  CatCatIdRoute: CatCatIdRoute,
  SubcatSubcatIdRoute: SubcatSubcatIdRoute,
  BrandsIndexRoute: BrandsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
